class PCRRule {
  final String ruleId;
  final String clauseReference;
  final String title;
  final String requirement;
  final String category;
  final String penaltyClause;
  final String severity;

  const PCRRule({
    required this.ruleId,
    required this.clauseReference,
    required this.title,
    required this.requirement,
    required this.category,
    required this.penaltyClause,
    required this.severity,
  });

  static const List<PCRRule> defaultRules = [
    PCRRule(
      ruleId: "RULE-6-1-A",
      clauseReference: "Rule 6(1)(a)",
      title: "Generic / Common Name of Commodity",
      requirement: "The name of the commodity contained in the package must be clearly stated on the Principal Display Panel (PDP).",
      category: "all",
      penaltyClause: "Section 36(1) of Legal Metrology Act, 2009 (Fine up to ₹25,000 for 1st offense, ₹50,000 for 2nd)",
      severity: "CRITICAL",
    ),
    PCRRule(
      ruleId: "RULE-6-1-B",
      clauseReference: "Rule 6(1)(b)",
      title: "Complete Name & Address of Manufacturer/Packer/Importer",
      requirement: "Full name and complete address of the manufacturer, packer, or importer must be clearly declared on the package.",
      category: "all",
      penaltyClause: "Section 36(1) of Legal Metrology Act, 2009",
      severity: "CRITICAL",
    ),
    PCRRule(
      ruleId: "RULE-6-1-C",
      clauseReference: "Rule 6(1)(c)",
      title: "Country of Origin for Imported Commodities",
      requirement: "For all imported packaged commodities, the name of the country of origin must be prominently declared.",
      category: "imported",
      penaltyClause: "Rule 6(1)(c) PCR 2011 & Section 36 LM Act",
      severity: "HIGH",
    ),
    PCRRule(
      ruleId: "RULE-6-1-D",
      clauseReference: "Rule 6(1)(d)",
      title: "Net Quantity & Standard Measurement Unit",
      requirement: "Net quantity declared in standard SI units (g, kg, ml, L, m, cm, pcs) with prescribed font height as per area of PDP.",
      category: "all",
      penaltyClause: "Section 36(2) of Legal Metrology Act, 2009",
      severity: "CRITICAL",
    ),
    PCRRule(
      ruleId: "RULE-6-1-E",
      clauseReference: "Rule 6(1)(e)",
      title: "Month & Year of Manufacture/Packing/Import",
      requirement: "Month and year in which the commodity is manufactured or packed or imported must be stated clearly as 'Mfg/Pkd: MM/YYYY'.",
      category: "all",
      penaltyClause: "Rule 6(1)(e) PCR 2011 & Section 36 LM Act",
      severity: "HIGH",
    ),
    PCRRule(
      ruleId: "RULE-6-1-F",
      clauseReference: "Rule 6(1)(f)",
      title: "Maximum Retail Price (MRP) Mandatory Declaration Format",
      requirement: "MRP declared as 'Maximum or Max. Retail Price Rs./₹ xx.xx (inclusive of all taxes)' in mandatory statutory format.",
      category: "all",
      penaltyClause: "Section 36(1) & (2) of Legal Metrology Act, 2009",
      severity: "CRITICAL",
    ),
    PCRRule(
      ruleId: "RULE-6-1-G",
      clauseReference: "Rule 6(1)(g)",
      title: "Consumer Care Cell Contact Details",
      requirement: "Name, address, telephone number, and email address of the person/office to be contacted in case of consumer complaints.",
      category: "all",
      penaltyClause: "Rule 6(1)(g) PCR 2011 & Section 36 LM Act",
      severity: "HIGH",
    ),
    PCRRule(
      ruleId: "RULE-6-1-H",
      clauseReference: "Rule 6(1)(h)",
      title: "Unit Sale Price (USP) Declaration",
      requirement: "Unit sale price per gram/kilogram/milliliter/liter/piece declared wherever net quantity exceeds 1kg or 1L.",
      category: "all",
      penaltyClause: "Rule 6(1)(h) PCR 2011 Amendment 2022",
      severity: "MEDIUM",
    ),
    PCRRule(
      ruleId: "RULE-6-2",
      clauseReference: "Rule 6(2)",
      title: "Minimum Height of Numerals & Letters Legibility",
      requirement: "Declarations must be legible, prominent, in contrasting color to background, with font height scaling relative to Principal Display Panel area.",
      category: "all",
      penaltyClause: "Rule 6(2) & Rule 9(1) PCR 2011",
      severity: "HIGH",
    ),
    PCRRule(
      ruleId: "RULE-6-3",
      clauseReference: "Rule 6(3)",
      title: "Principal Display Panel (PDP) Contrast & Prominence",
      requirement: "All mandatory declarations must be grouped together on the PDP and clearly visible against the background container color.",
      category: "all",
      penaltyClause: "Rule 6(3) PCR 2011",
      severity: "MEDIUM",
    ),
    PCRRule(
      ruleId: "RULE-7",
      clauseReference: "Rule 7",
      title: "Multi-piece & Combination Package Declaration",
      requirement: "Wholesale or multi-piece packages containing individual items must state total number of pieces and net quantity per piece.",
      category: "pre-packaged",
      penaltyClause: "Rule 7 PCR 2011",
      severity: "HIGH",
    ),
    PCRRule(
      ruleId: "RULE-8",
      clauseReference: "Rule 8",
      title: "Standard Symbols of Measurement Units",
      requirement: "Only standard legal SI unit symbols (kg, g, L, ml, m, cm, mm) are permitted. Non-standard abbreviations (e.g. gms, kgs, ltr) are prohibited.",
      category: "all",
      penaltyClause: "Rule 8 PCR 2011 & Section 11 LM Act 2009",
      severity: "MEDIUM",
    ),
    PCRRule(
      ruleId: "RULE-9",
      clauseReference: "Rule 9",
      title: "Prohibition of Misleading Declarations",
      requirement: "No declaration on a package shall be false, misleading, or deceptive regarding weight, measure, or price.",
      category: "all",
      penaltyClause: "Section 36(1) of Legal Metrology Act, 2009",
      severity: "CRITICAL",
    ),
    PCRRule(
      ruleId: "RULE-18",
      clauseReference: "Rule 18(2)",
      title: "Prohibition of Overcharging Above Declared MRP",
      requirement: "No retail store, dealer, or e-commerce platform shall sell any packaged commodity at a price exceeding the declared MRP.",
      category: "all",
      penaltyClause: "Section 36(2) of Legal Metrology Act, 2009 (Fine up to ₹2,000 to ₹50,000 or imprisonment up to 1 year)",
      severity: "CRITICAL",
    ),
    PCRRule(
      ruleId: "RULE-26",
      clauseReference: "Rule 26",
      title: "Exemptions for Small Packages",
      requirement: "Packages with net weight/volume of 10g or 10ml or less are exempt from certain statutory declarations except name of commodity and manufacturer.",
      category: "all",
      penaltyClause: "Rule 26 PCR 2011",
      severity: "LOW",
    ),
    PCRRule(
      ruleId: "RULE-32",
      clauseReference: "Rule 32",
      title: "Enforcement Penalty for Sale of Non-Compliant Packages",
      requirement: "Whoever manufactures, packs, imports, sells, or distributes non-compliant packages shall be punished under Section 36 of LM Act 2009.",
      category: "all",
      penaltyClause: "Section 36 Legal Metrology Act, 2009",
      severity: "CRITICAL",
    ),
  ];
}
